# This Dockerfile is used to make easy the local development using PostgreSQL
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: codapdf
      POSTGRES_PASSWORD: codapdf
      POSTGRES_DB: codapdf
    ports:
      - "5433:5432" # Change the host port to 5433
    volumes:
      - data:/var/lib/postgresql/data  # Persist database data
    networks:
      - codapdf_network
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data 
networks:
  codapdf_network:
    driver: bridge
volumes:
  data:
  dragonflydata: